### ISSUE TITLE
Apple Watch Complications use?

### ISSUE THREAD

**Issue by KmanOz** [sebbu/iControl-Web#1]
Hi Sebastian. Thanks for the update. Just one question. I notice you have added Complications. The small complication just displays an ON logo and seems like a handy way to launch the App. My question is about the large Complication. Does it do anything? Seems like there is room for text but currently it's filled with 24 underlines, like it's waiting for data. Does it actually work?

Peter

**Comment by sebbu** [comment]
Hi Peter, The large complication is currently not really supported. It looks the same on my watch.
