### ISSUE TITLE
Is iControl crashing or being flushed from memory on Apple Watch?

### ISSUE THREAD

**Issue by ahwman** [sebbu/iControl-Web#10]
Hello,

I changed the default wrist raise behavior to show the last used app vs. the clock face so I don't constantly have to keep relaunching iControl.  That said, I've noticed that every once and a while, the app will close and return to the watch face without any interaction on my part.  Sometimes it happens while it's loaded and idle and other times upon raising my wrist.  When this happens and I reload the app, it doesn't remember where I left off in the app almost as though it's been flushed from memory.

Any ideas?

Thank you!
Chuck

**Comment by sebbu** [comment]
There was a potential issue which was fixed in 1.6
