### ISSUE TITLE
config won't be transferred to watch

### ISSUE THREAD

**Issue by ede-kowalski** [sebbu/iControl-Web#11]
Hi,

I installed the app yesterday from itunes, installed it to my watch and afterwards i edited the config.
Tried to upload the config again, but that doesn't work. Each time i am starting the upload via the app, close app and restart it, i am getting the message that the config will be transferred and afterwards, that it was transferred. But the date is yesterday morning (date of installation).
The new config version wasn't transferred to the watch.

Already rebooted both devices, reinstalled it.

Any idea?

regards,
Ede

**Comment by ahwman** [comment]
I assume you named the config file gui before uploading?

**Comment by sebbu** [comment]
the file must be named gui.json. Did you follow the instructions on github step by step?

I have had the issue that the app was somehow not completely installed on the watch. Uninstall the app on the watch and the iPhone. reboot boot, install it again on the iPhone (make sure you have good wifi for both devices, so the app is also installed correctly on the watch).

**Comment by ede-kowalski** [comment]
gui.json is correct (phone Shows everything correct).
But even after reinstalling and rebooting i am getting message from my phone that the config will be transferred and afterwards, that it was transferred last sunday...

Watch showed no config at all and now it's showing the Default view.

**Comment by ede-kowalski** [comment]
if i am changing the config again, Transfer starts, and i am getting correct upload date. But at the watch, everything is like there is only the sample config...

**Comment by sebbu** [comment]
which watchOS version do you use?

**Comment by ede-kowalski** [comment]
2.2.1

**Comment by sebbu** [comment]
I have just tested it today and everything works fine for me. Can you make sure that the json is not broken. Maybe we start it all over again. please do the following steps:

- Uninstall the app on the watch
- Uninstall the app on the iPhone.
- Reboot both
- install the app on the iPhone
- it is automatically on the watch
- watch says no config
- make a copy of guiSample.json on your computer and only rename a headline in iPhone and watch config to ensure that the app reads it.
- rename the file guiSample.json to gui.json on your computer
- remove the guiSample.json file from the iPhone (right click in iTunes files sharing on the file or hit DEL or cmd+backspace)
- copy your modified gui.json to the iPhone
- follow the steps as described https://github.com/sebbu/iControl-Web to sync the config
- sometimes you need to stop and start the app a second time on the watch to see the changes.

I will bring out an update of the app soon, but I am sure that there are no fixes for the transfer in it.

**Comment by ede-kowalski** [comment]
tried the steps like described, no chance. change in gui.json was shown on the phone, watch showed no config. Then I transferred config and the sample was shown...
Seems like the sample config was stored at the watch somehow...maybe i need to reset it completely.

**Comment by sebbu** [comment]
Version 1.7 is on the way. Give it another try. 

There is a "transfer again"-button on info screen. Make sure that you stop the app AND swipe it out of the task switcher!
