### ISSUE TITLE
Configuration sometimes lost on AW after reboot

### ISSUE THREAD

**Issue by ahwman** [sebbu/iControl-Web#15]
I'm loving this app and use it daily and thank you for all of your hard work!  That said, I've noticed that sometimes after rebooting my Apple Watch/iPhone, the configuration is lost on the Apple Watch and have to go back to the iControl app on my iPhone and transfer the configuration back to the watch again.  Any reason why this might be happening?

Thanks so much,
Chuck

**Comment by sebbu** [comment]
Hi Chuck,

I never turn off my watch (and therefore do not reboot). I will check on the issue. Probably a bug.

**Comment by ahwman** [comment]
Thank you!

**Comment by sebbu** [comment]
I have just double checked the code and there is no obvious bug as the code looks trivial. What is the exact message?
"No config all" or "No config controls". Or does it show the example UI?

**Comment by ahwman** [comment]
"No config all"
