### ISSUE TITLE
Feature Request: Ability to send multiple commands with one button

### ISSUE THREAD

**Issue by hugoender** [sebbu/iControl-Web#17]
Let me know if this is already possible but if not, it would be a great feature. For example, I can have a button that when pressed, opens the garage door and then turns on a light instead of have to press one button for garage door and a second button for the light.

Thank you.

**Comment by sebbu** [comment]
Hello Hugo, I understand your use-case but I think this should be done in the backend.

I understand the need if somebody wants to send a request when the button is pressed down and another request when the button is released. 

But in your case I would propose you do it in your backend. I use a raspberry and run my simple server: 
[RaspberryPi GPIO WebControl](https://bitbucket.org/sbub/raspberry-pi-gpio-web-control)
The server can act as a proxy: You could simple create a shell script and add multiple curl commands to it and configure the cmd.conf to send multiple requests.
