### ISSUE TITLE
Sometimes first button click doesn't respond

### ISSUE THREAD

**Issue by ahwman** [sebbu/iControl-Web#18]
Love the app and use it daily!  That said, for some reason often times button presses don't respond on the first press.  Example, opening up the app the first button press works as expected, however after the app remains open and the watch screen goes to sleep, resuming the app and pressing a button results in no response.  Pressing any button a second time responds normally...

Any ideas as to what is causing this issue?

Thanks so much,
Chuck

**Comment by sebbu** [comment]
I believe it is nothing about the app. I have also seen it for other apps. I have added the haptic feedback to know when the button was pressed. I have made the experience that the first request takes long (maybe WIFI on the watch).

**Comment by ahwman** [comment]
Thanks for the reply.  I love this app and that seem to be the only hickup I experience.  Perhaps Apple will address this in the future...

Thanks again!
Chuck

**Comment by sebbu** [comment]
Hi. The future came.

Do you still have these hickups
