### ISSUE TITLE
Add support for SSL client authentication

### ISSUE THREAD

**Issue by farfade** [sebbu/iControl-Web#19]
Hello,

Thanks for the great work 👍 

Would it be possible to add support for SSL client authentication ? I've installed a client certificate in the iphone certificate store. Safari manages to use it when connecting to a webserver requiring client authentication, but iControl-Web fails (by timeout).

**Comment by sebbu** [comment]
Hi,

I understand your request for client side certificates, but as a Third Party App developer, I do not have access to the Safaris certificate store.
As stated here:
https://developer.apple.com/library/content/documentation/Security/Conceptual/cryptoservices/KeyManagementAPIs/KeyManagementAPIs.html
"In iOS, an app can access only its own items in the keychain—the user is never asked for permission or for a password."

Concerning security I have always had the following idea:
Do not make your server available in the Internet (through something often called virtual server), but just let it have a private IP.
Create some infrastructure around it for the access, i.e. a VPN. If you search for VPN configuration, I think that it is possible (with Apple Configurator 2) to manage VPN and have it auto connect for certain hosts (i.e. your dyndns hostname of your router).
You will probably have a problem with this config if you are at home (and the VPN won't work).

Currently I am not planing to support client side certificates as it is not easy to write and hard to debug for the user.
