### ISSUE TITLE
New request

### ISSUE THREAD

**Issue by Rubendran** [sebbu/iControl-Web#2]
Not sure if I'm logging this in the write place. First of all great app, what can we done with in. 
I wanted to request some additional features:
  A star / plus configuration of 5 buttons for directional control and select
  A grid layout of potentially 4x4 or 5x5 of square buttons
Some additional icons / documentation / guidance on how you manage icons/mages in the json

I am willing to support with development, testing and even donations if required.

Thanks. And great app!

**Comment by sebbu** [comment]
Hi,

I take the feature requests with me. 

The Icons are normal emojis as people use them in messengers. Simply copy/paste them to the json.

Thanks, Sebastian

**Comment by pvangerwen** [comment]
Hi, icons are indeed normal emojis. I insert them with UTF-16 escape codes,
e.g. "\uD83C\uDF4E" for an apple. \uD83C\uDF4E
You can find the codes for different emojis on different websites, I used http://www.iemoji.com/view/emoji
Good luck,
Peter

**Comment by sebbu** [comment]
Thanks for the link. Please keep in mind that emojis might look different on the phone than on the web where you have chosen it: https://medium.com/matter/lost-in-emoji-translation-apple-vs-android-648fdd57ca25#.7ojoeaeel
