### ISSUE TITLE
POST Method

### ISSUE THREAD

**Issue by NicAshby** [sebbu/iControl-Web#20]
Some of my commands require a POST method instead of GET.
I don't see any documentation allowing this.
Is this possible currently?
If not, please add.

**Comment by sebbu** [comment]
Hi, I am really struggling with a sweet solution which really works for many user. I think: the data of the POST request currently offers to many possibilities to make a good generic solution.

What kind of data is required for you? 
application/x-www-form-urlencoded
multipart/form-data
application/json

I would think you could just get you a Rasperry PI and implement a little proxy which takes GET requests and sends POST requests on the other side. You could easily implement it with mine:
https://bitbucket.org/sbub/raspberry-pi-gpio-web-control and only use "External commands/scripts" and add a curl to the script.

**Comment by NicAshby** [comment]
I don't have any data to be sent with the HTTP_POST.  It's just required by my IR server. 

I've considered the solution you've suggested but am reluctant to implement that extra layer due to the added bloat a system I am trying to keep as minimal as possible. 

I appreciate your reply and hope you can find a way to implement a bare-bones http-method if only just to make the method available without the extra frills. 

-Nic

**Comment by sprokkie** [comment]
any news about the post command ?
i need it for my aplication also
