### ISSUE TITLE
Collaboration/open source

### ISSUE THREAD

**Issue by leeogrady** [sebbu/iControl-Web#23]
Hi,
I see this project hasn't been touched in a while, are you interested in opening the source or wanting someone to collaborate on this with you?

Cheers

**Comment by aivs** [comment]
Sebbu please open sourse, I'll add a basic auth!

**Comment by Arthur31** [comment]
I'm also interest by source code 
Please open source 🙏🏻

**Comment by sebbu** [comment]
Please,contact me directly @aivs and @Arthur31 via mail.

**Comment by jackjameshoward** [comment]
Any further consideration to making this open source?

**Comment by luckydonald** [comment]
This sounds fantastic

**Comment by Torac2** [comment]
Does anyone know?
How do i use the command function e.g i make an command how do i use it?
http://raspberrypi:8080/handle?CMDnotify=1
Doesnt work.

Love the app itself btw!

**Comment by MarvAmBass** [comment]
would be really nice 🙏

**Comment by sammosna** [comment]
+1

**Comment by satrik** [comment]
Hi Sebbu,
i'm also interested in helping. How is your mail address?

**Comment by sebbu** [comment]
Hi, schreib mir einfach eine Mail. Dann können wir alles besprechen.
