### ISSUE TITLE
How to get feedback from digital input from denkovi relayboard

### ISSUE THREAD

**Issue by Ryger** [sebbu/iControl-Web#25]
Hello
I am a newbie in this(and in english)
I will use this program to open garagedoors with denkovi DAEnetIP4 relay card.
I can now open and close the doors and turn on and of the light in the garage, but what i dont understand is how to make a status light in the app so i can see that the doors is locked and the lights is turned off. (one light for each door and one for the light)
Is this possible in this app?

**Comment by sebbu** [comment]
Hi. 

In the current version it is not possible. 

You can only add ‚actions‘, no ‚sensors‘. 

This mainly due to time constraints not yet implemented because I offer the app completely free.
