### ISSUE TITLE
Ability to customize via iOS “share” dialog

### ISSUE THREAD

**Issue by Patronics** [sebbu/iControl-Web#27]
It would be useful to be able to customize this app on the device itself, by creating the JSON in another app, and importing it directly, independently of iTunes. If this app was open source (as I thought it was initially upon being linked to github), I (and others) could try to contribute to it directly.

**Comment by sebbu** [comment]
Hi, this is possible. Please read the following section https://github.com/sebbu/iControl-Web#json-file-via-email-or-any-file-based-cloud-app

"....You can also use any other (file based cloud) app, i.e. iCloud, Dropbox, to send/export the file iControl Web. ...."
