### ISSUE TITLE
Problem with http controlling home automation and icontrol via watch

### ISSUE THREAD

**Issue by boehlinet** [sebbu/iControl-Web#28]
Hi sebu
First thanks for the APP.
I have now configurated my gui.JSON, so i send it via itunes to the watch - OK
I will send a http request to my Home Automation.
In a browser the http String works perfectly.
But when i press the Button on the Watch, nothing comes up on my Homeautomation.
What ist the problem ? Can you help me please ?
WIFI an all other links are OK

many thanks
here is an example from my programming:

	{
          "button1": "Szene Test",
          "cmd1": "http://192.168.1.200/index.html?W&Name=MAIN.test&Type=BOOL&Value=1",
          "sizeType": "large",
          "color": "green"
        }

Rene

**Comment by sebbu** [comment]
hi,

at a first glance, it looks fine. Try to remove all Umlauts (Böh...) and strip the config downto find the error. Sometimes loading and/or reloading of the config does not work (if you only change the url, but not the UI, you might be testing an old config).

`{
  "showInfoScreen": true,
  "coloredNetworkFeedback": true,
  "pages": [
    {
      "pageLabel": "EFH",
      "timeout": 2,
      "compactHeight": false,
      "controls": [
        {
          "button1": "TEST",
          "cmd1": "http://192.168.1.200/index.html?W&Name=MAIN.test&Type=BOOL&Value=1",
          "headline1": "Szene Test",
          "sizeType": "large"
        }
      ]
    }
  ],
  "pagesWatch": [
    {
      "timeout": 2,
      "hapticNetworkResponseFeedback": true,
      "pageLabel": "EFH",
      "controls": [
        {
          "button1": "Szene Test",
          "cmd1": "http://192.168.1.200/index.html?W&Name=MAIN.test&Type=BOOL&Value=1",
          "sizeType": "large",
          "color": "green"
        }
      ]
    }
  ]
}`

**Comment by boehlinet** [comment]
Hi Sebastian
Kannst du das auch auf Deutsch erklären ?
Ich glaube nicht das ich einen Fehler drinnen habe.
Danke

LG Rene

www.boehli.net
_____________________________

**Comment by sebbu** [comment]
Bist du sicher, dass die Konfiguration wirklich neu geladen wurde?
Ist die Uhr im richtigen WLAN?
Ist das lokale Netzwerk korrekt? (zB MAC Adressen Sicherung und Uhr nicht erlaubt, Routing)
Ggf. nochmal das Timeout erhöhen (unterhalb von pagesWatch). 

Eigentlich wird die URL nicht interpretiert, allerdings ist ...?W&... ungewöhnlich (der Key W ohne Wert). Geht das ggf. anders?

**Comment by boehlinet** [comment]
hallo sebastian,
ich betreibe eine Beckhoff Steuerung, ich sprechen mit dem link einen webserver an.
Der Link passt so wie ich ihn habe.
http://192.168.1.200/index.html?W&Name=MAIN.test&Type=BOOL&Value=1
ipadressedersps/webserverindex/Write&Name=OrtDerVariable=BOOL&Value=1 ich sezte in der sps auf 0 zurück

Ja im richtigen WLAN alles getestet
Auch habe ich die gui.JSON nochmals überarbeitet und die Umlaute rausgenommen bzw. angepasst.
Keine Funktion nach Download
TimeOut habe ich auf 5 gestellt
im anhang das ZIP

[gui.zip](https://github.com/sebbu/iControl-Web/files/1594422/gui.zip)

**Comment by sebbu** [comment]
1.
Wie ist denn das haitische Feedback? Erfolgreich = 1x kurzes brummen bei Tap und 1x langes brummen nach kurzer Zeit (wenn Befehl abgesendet)

oder 1x kurz und dann 2x kurz?

2.
Funktioniert es vom iPhone aus?

3.
Könntest du den "SzeneTest" Knopf anstatt als letzten mal als ersten konfigurieren? Vielleicht wird eins der vorherigen Elemente nicht richtig interpretiert. 

4.
Hast du ein log von der Hausautomation wo du reingucken kannst? Oder könntest du dir lokal einen Webserver installieren und ins log gucken, was die Uhr sendet und was das iPhone sendet?

5.
Ist dein IPv4/IPv6 richtig konfiguriert? Vielleicht könntest du statt der IP einen Namen verwendet. Häufig kann man (zB in der Fritzbox) den Geräten einen Namen geben.

**Comment by boehlinet** [comment]
Hallo Sebastian ,

Meine Antworten unten
Hoffe diese helfen dir

Kann es eventuell am IOS Version liegen ?
Weil folgendes sehe ich im APP am iPhone meiner watch:

[Image]

LG Rene

www.boehli.net
_____________________________

**Comment by sebbu** [comment]
Das haptische Feedback bedeutet, dass irgendwer mit HTTP 200 antwortet 

Wenn du auf dem iPhone und iPad den gleichen TV-Befehl verwendest (welcher auf dem iPad geht und du ` "coloredNetworkFeedback": true,` wird dann der Button nach klick auch auf dem iPhone kurz grün?

Wenn ein Befehl auf dem iPad geht und auf dem iPhone nicht und du im Server-Log nichts siehst, dann würde ich immer noch behaupten, dass irgendwas mit dem Netzwerk komisch ist. 

Ist im iPhone für das WLAN noch ein Proxy konfiguriert? 

Oder ist ggf. WLAN-Assist an? https://support.apple.com/de-de/HT205296

**Comment by boehlinet** [comment]
Hallo Sebastian,
Ich konnte nun die Problematik lösen. Ich habe mir einfach ein node.js auf meinem Leitrechner am laufen, dies empfaängt von der iWatch die Befehle und sendet es an meine Steuerung weiter.
So long
Danke
Ich schliesse den Thread

LG Rene
