### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by pvangerwen** [sebbu/iControl-Web#3]
Dear,
I'm trying your app with my PHC system, and it's really cool.
However, two questions:
1/ I have to set the timeout to really long (I'm using 8 now, 2 didn't work), and after I push a button, it does the required action (which works, so that's great), but then it gives a "red" feedback, and gives an error message "Error: Failed with error. The network connection was lost." Any idea what this could be?
2/ The apple watch app doesn't work... I can define a nice screen, but when I push the button, nothing happens (are is this related to the first error?)
Thank you,
Peter

**Comment by sebbu** [comment]
Hi, on your first issue: I have seen something similar with a PEHA PHC. It seems that PEHA did not fully implement HTTP responses. Your PHC system handles the request, but does not respond correctly. The App does not know if the common succeeded. Simply turn off all error alerts: Turn off the popup (Show error messages) on the info screen and set the coloredNetworkFeedback to false (as it would always flash red even on a success). On the Apple watch, the hapticNetworkResponseFeedback will also respond with an error.
2. On the watch you also have to specify your timeout. Did you also set it? The first error might be related, but I know of a happy watch user with a PHC system.

**Comment by pvangerwen** [comment]
Thank you for the feedback! The iphone app is now working great. I'm still trying for the watch.

**Comment by blowdesign** [comment]
hi,

Congratulations for your work.
I've a question for my PHC system. I've an old controller with only a USB port not a RJ45 port. I've try to connect the controller to my routeur with a converter USB-RJ45 but it doesn't work, it doesn't received any IP. 
So what is the solution ? I've a Linux server (Ubuntu 12.04) near the controller. May I connect the controller to my server with the USB port and use usb over IP ?

Thanks in advance,

**Comment by sebbu** [comment]
hi,

this is very PHC specific and does not have anything to do with iControl Web. Please ask in a PHC system forum.
