### ISSUE TITLE
Apple Watch Transfer

### ISSUE THREAD

**Issue by yufretti** [sebbu/iControl-Web#35]
Hi all,
I'm having a problem with transferring the configuration to my Apple Watch. When I open the App on iPhone, the message "synchronization with apple watch completed" never appears and the message "No config all" is always on the watch.
How can I transfer the configuration to my Watch?
On my iPhone I installed IOS12 and on Watch WhatchOS5.
I tried to transfer the gui.json file by copying the test file in the manual.
Thank you

Yuri

**Comment by sebbu** [comment]
Hi, I have not checked if it is working with iOS12 and watchOS5 correctly. I will look into it (hopefully I make it this week).

The message appears if no data is available or if the json ist corrupted. Did you check with a json editor that the structure is valid? If it is a valid json structure (but a different json), you will see "No config controls".

**Comment by yufretti** [comment]
I uninstalled and installed the application on both watch and iphone and started working.
Congratulations for your app. It is really very powerful.
Thank you.
Yuri

**Comment by danilodene** [comment]
Here works like charm on iOS 12 and watchOS 5

**Comment by sebbu** [comment]
It rarely happens. Good to know that it works know
