### ISSUE TITLE
Apple Watch Coplication ? Infographie

### ISSUE THREAD

**Issue by chocorem** [sebbu/iControl-Web#38]
I'm getting trouble finding The complication on my apple watch ? on the New info graphe and on the old faces ?

**Comment by sebbu** [comment]
Does it work on some or not at all?

**Comment by chocorem** [comment]
I tried
On all the faces I have ,
None are working. Do you perhaps have a faces where you are sure it is working , so that I can test ?

**Comment by chocorem** [comment]
Hello, Any news about this ? The little infographie complications  Still do not work !

**Comment by sebbu** [comment]
Please check version 1.8....
I know that the logo is missing on old watches (but the "click" still works).
