### ISSUE TITLE
Arduino help

### ISSUE THREAD

**Issue by erasmudj** [sebbu/iControl-Web#41]
Can you please guide me in the right direction to have the app work with an arduino?

I don't find useful information on the web on how to uset the http cmd with an arduino.

**Comment by sebbu** [comment]
Arduino have to run a http server on your Arduino and you need a network connection for your Arduino (i.e. Wifi).

You can configure a button in the app which calls a dedicated http(s) url. If the url points to your Arduino, you can control it with the app (in your local wifi).

If you want to reach your Arduino from anywhere on the internet, you need additional configuration (i.e. VPN on your phone which points to the same network where you can reach the Arduino OR ReverseProxy configuration in your router, ...).
