### ISSUE TITLE
Feature Request: Quick Page Links

### ISSUE THREAD

**Issue by raceviper13a** [sebbu/iControl-Web#44]
Is there any way a feature can be added? I'd like a quick way to be able to go to a particular page with a single press?

Options include:

1. Button commands that can be created on pages to go to particular pages.
2. Tabs at the top or bottom to link to pages.
3. Something else?

Preferably, it would be nice to be able to label each page link, or use the existing label at the top of the page using the ["pageLabel":].  If there are a lot of pages, it would be nice to be able to use just an icon like 🛌 so that the label is short for compactness.

**Comment by sebbu** [comment]
Do I get you right that you have so many pages, that you need a navigation?

**Comment by raceviper13a** [comment]
There are many pages, and the pages I have are long.  They each take a while to display.  Cycling through them all takes a while.  Plus, it can be easy to forget which one you are on since they are all controlling the same radio stations, but for different devices.  Each device has an identical page of radio stations.  The only difference is the text at the top of the long page.

**Comment by sebbu** [comment]
Can you pls send me a private message and we discuss this issue directly.

btw you can not use icons, but you can use emojis/unicode icons.
