### ISSUE TITLE
discovered an error?

### ISSUE THREAD

**Issue by pvangerwen** [sebbu/iControl-Web#5]
Hi,
I discovered a potential error.
Initially, I had controls in my phone just to turn on or turn off something. That worked great!
Recently, I added a control that toggled an output.
When pressing the button on my phone, it switches the light on and off multiple times (uncontrolled number), so it seems to me that when pressing the button, the web command is sent multiple times.
(That's maybe also the reason why the PHC controller doesn't reply. The commands are fired too quickly... Even with the delay set to a significant amount).
Was a switch debounce algorithm implemented ? (for examples ,see e.g. http://www.embedded.com/electronics-blogs/break-points/4024981/My-favorite-software-debouncers)
Kind regards,
Peter

**Comment by sebbu** [comment]
Hi,

there is no "delay" feature for requests. You can specify a timeout, but it is the waiting time for responses. In the gui-sample.json file there is a simple add/subtract service. I have tested and I can not see multiple requests. You can test the URL in a browser without parameters to get the current state. 

I will put the debounce feature on the feature list as it sounds reasonable.

Regards, Sebastian
