### ISSUE TITLE
Version iWatch 2.2

### ISSUE THREAD

**Issue by pocket998** [sebbu/iControl-Web#6]
Hello, 

I upgrade my iWatch on version 2.2 now application open and close directly (on iWatch)

I need change parameters on file or is application is not compatible with version 2.2?

Tanks for sour support and Nice application !!!!!

**Comment by sebbu** [comment]
Hi, I have tested it and it works on my watch. I propose the following:

Check your json against a json editor (i.e. http://jsoneditoronline.org/).
Uninstall app on you watch and install it again.
If it still occurs, you can send me your crash report

**Comment by pocket998** [comment]
Hi,
I have uninstall and install again but not working.
I put json file standard but not working.

**Comment by pocket998** [comment]
For send crash report I found the file how ?

Thanks

**Comment by sebbu** [comment]
Directly on the phone: Here are instructions: https://developer.apple.com/library/ios/qa/qa1747/_index.html

The technical app name is: httpremoteWatchOS2*

**Comment by sebbu** [comment]
Should have been fixed with version 1.6
