### ISSUE TITLE
Haptic feedback continues after disabling switch

### ISSUE THREAD

**Issue by ahwman** [sebbu/iControl-Web#7]
• First off, I must congratulate and thank you for a truly awesome application!  That said, I set the haptic feedback switch for Apple Watch to false yet I continue to get haptic feedback upon button presses.

• Also, is there any way to disable the chime sound after button presses?

Thanks again for all of your effort on a truly useful app,
Chuck

**Comment by sebbu** [comment]
Hi Chuck,

thanks for reporting the bug. It is a known issue and actually already fixed. I need to release a new version. Sound will also be turned off with the same property.

**Comment by sebbu** [comment]
His was fixed in version 1.6
