### ISSUE TITLE
Didn't know where to post this question?

### ISSUE THREAD

**Issue by ahwman** [sebbu/iControl-Web#8]
I noticed some emoji icons placed in the sample templates and would like to add some of my own.  Where can we find a list of available emoji icons and their  corresponding key codes?

Thanks so much!
Chuck

**Comment by sebbu** [comment]
Hi. Just search for it on Google or use some kind of emoji app. Afterward copy/paste the icon to the configure file.

**Comment by ahwman** [comment]
When I copy the emoji into the config file, all I get is "??"' in the text field.

**Comment by sebbu** [comment]
Make sure you use a text editor which can handle utf-8 correctly. it sounds like you are using one which opens/saves your file as iso8859-1 or something else

**Comment by ahwman** [comment]
Got it working.  I was trying to paste emoji's directly into the json editor I was using.  Using a text editor did the trick!  Thanks so much...

Chuck
